name: heroes_companion_data
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Arran France <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: "^0.4.0"
  http: "^0.11.3"
  hots_dog_api: "^1.0.7"
  path_provider: "^0.3.0"
  shared_preferences: "^0.3.1"

dev_dependencies:
  test: ^0.12.0
